### ISSUE TITLE
Installing qp code

### ISSUE THREAD

**Issue by addman2** [TREX-CoE/aiida-qp2#4]
How can I setup my aiida code? When I cannot simply `bash` because `qp` function will not be passed into the aiida script. Do you have any advise how to prepare the code?

**Comment by q-posev** [comment]
Hi @addman2,
Not sure I understand your question. In the current setup, the `qp` commans is prepended to all commands that you provide in the aiida scripts (see `examples` directory).
Now, how you are going to setup your AiiDA depends on the machine where you run. On CALMIP, I deployed a singularity container with QP2 installed and with `qpsh` as an entry-point. It worked well, but it was also >2 years ago and before aiida 2.0 release.
I might still have the YAML configs for CALMIP, let me know if you need them. Here is my outdated repo with Singularity `.def` files: https://github.com/q-posev/qp2-singularity . It won't build out of the box cause you need to use `dev-stable` branch of QP nowadays. I might have a working Dockerfile though :-)

**Comment by addman2** [comment]
Thanks @q-posev , basically, the issue I had is how to install the code (which is missing in the ``examples``). Well I made a workaround. But the question is what should be the full path to the executable. Since ``aiida-qp2`` creates a bash script naturally one would expect something like ``/usr/bin/env bash``. However you can pass the environment variabale to the bash interpreter, but ``qp`` is a function and functions are not passed to the new interpreter. Therefore one would need to source ``rc`` file, but to my surprise according to ``man bash`` it is not that easy.

**Comment by q-posev** [comment]
I see, yes `examples` show examples of usage, not setup.
I personally find that it's easier to deploy QP in a container due to the zoo of dependencies. 
For your problem - yes, you always need to `source quantum_package.rc` file before running QP. It is done automatically in the container. Now, the `aiida-qp2` plugin is quite flexible. What you can do is you can source `rc` file as part of `qp_prepend` mechanism which I implemented [here](https://github.com/TREX-CoE/aiida-qp2/blob/master/aiida_qp2/calculations.py#L231). 

When you setup the builder, add the following to the `options` dict (you have to adapt the path for your installation):
```python
{
  'qp_prepend': 'source $PATH_TO_RC/quantum_package.rc'
}
```

It is not well documented, but you can get some inspiration from the QMC=Chem [example](https://github.com/TREX-CoE/aiida-qp2/blob/master/examples/example_trexio_from_xyz.py#L125)
